Description: Database for Norcloud Demo

Parameters:
  Subnets:
    Description: Subnets for Database
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroups:
    Description: Security Group for Database
    Type: List<AWS::EC2::SecurityGroup::Id>

  DatabaseName:
    Description: Database Name
    Type: String

  DatabaseUser:
    Description: Database User
    Type: String

  DatabasePassword:
    Description: Database Password
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - Subnets
          - SecurityGroups
      - Label:
          default: "Database Configuration"
        Parameters:
          - DatabaseName
          - DatabaseUser
          - DatabasePassword

Resources:
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Ref DatabaseName
      DBSubnetGroupName: !Ref DatabaseName
      SubnetIds: !Ref Subnets

  RdsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      BackupRetentionPeriod: 7
      DBInstanceIdentifier: !Ref DatabaseName
      DBInstanceClass: db.t2.micro
      DBName: !Ref DatabaseName
      DBSubnetGroupName: !Ref RdsSubnetGroup
      DeleteAutomatedBackups: true
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      MultiAZ: true
      PubliclyAccessible: true
      VPCSecurityGroups: !Ref SecurityGroups
    DeletionPolicy: Delete

Outputs:
  Endpoint:
    Description: Endpoint Url
    Value: !GetAtt RdsDatabase.Endpoint.Address
